name: Feature request
description: Solicitar nova funcionalidade
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema a resolver
      description: Qual dor atual?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposta
      description: Como você imagina a solução?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de aceite
      description: Como saberemos que está pronto?
