import React from 'react';
import './TestComponent.css';

interface TestComponentProps {
    title?: string;
}

export const TestComponent: React.FC<TestComponentProps> = ({ title }) => {
    return (
        <div className="testcomponent-container">
            {title && <h2>{title}</h2>}
            <p>TestComponent component generated by AI Tool.</p>
        </div>
    );
};
