import fs from "fs";
import path from "path";
import { pathToFileURL } from "url";

function emit(payload, exitCode = 0) {
  console.log(JSON.stringify(payload, null, 2));
  process.exitCode = exitCode;
}

function isValidComponentName(name) {
  return /^[A-Z][A-Za-z0-9]*$/.test(name);
}

function createReactComponent(name, targetDir = "./src/components") {
  if (!isValidComponentName(name)) {
    return {
      status: "error",
      error: "Invalid component name. Use PascalCase (e.g., ButtonCard).",
      data: { usage: "node react_scaffold.js <PascalCaseName> [targetDir]" }
    };
  }

  const baseDir = path.resolve(targetDir);
  const componentDir = path.join(baseDir, name);
  fs.mkdirSync(componentDir, { recursive: true });

  const tsxContent = `import React from 'react';
import './${name}.css';

interface ${name}Props {
    title?: string;
}

export const ${name}: React.FC<${name}Props> = ({ title }) => {
    return (
        <div className="${name.toLowerCase()}-container">
            {title && <h2>{title}</h2>}
            <p>${name} component generated by AI Tool.</p>
        </div>
    );
};
`;

  const cssContent = `.${name.toLowerCase()}-container {
    padding: 1rem;
    border: 1px solid #ccc;
    border-radius: 4px;
}
`;

  const indexContent = `export * from './${name}';\n`;

  fs.writeFileSync(path.join(componentDir, `${name}.tsx`), tsxContent, "utf8");
  fs.writeFileSync(path.join(componentDir, `${name}.css`), cssContent, "utf8");
  fs.writeFileSync(path.join(componentDir, "index.ts"), indexContent, "utf8");

  return {
    status: "success",
    error: null,
    data: {
      component: name,
      path: componentDir,
      files: [`${name}.tsx`, `${name}.css`, "index.ts"]
    }
  };
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    emit(
      {
        status: "error",
        error: "Please provide a component name.",
        data: { usage: "node react_scaffold.js <PascalCaseName> [targetDir]" }
      },
      2
    );
  } else {
    const result = createReactComponent(args[0], args[1]);
    emit(result, result.status === "success" ? 0 : 2);
  }
}

export { createReactComponent, isValidComponentName };
